name: Windows Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     VehTools.zip
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          requested: "5.15"
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules: 'qtcore qtwidgets qtgui'
          setup-python: false 
          

      - name: (4) Set Qt Environment Variables
        run: |
          echo "Setting Qt Environment Variables"
             echo "QTDIR=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/msvc2019_64" >> $GITHUB_ENV
             echo "QtToolsPath=${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/msvc2019_64/bin" >> $GITHUB_ENV
        shell: bash

      - name: (5) Download JOM
        uses: suisei-cn/actions-download-file@v1
        with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

      - name: (6) Unzip JOM
        working-directory: ${{ runner.temp }}
        run:  |
              7z x jom.zip -ojom

      - name: (7) Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
              
      - name: (8) Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: (9) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: (10) Build
        working-directory: ${{ runner.temp }}\build
        run:  |
              echo "Current directory: $($PWD.Path)"
              msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:OutDir=${{ runner.temp }}\build\ "${{ env.SOURCE_DIR }}\VehTools.sln"
              
      - name: (11) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a VehTools.zip ${{ runner.temp }}\build\* -r
              
      - name: (12) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
